# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .resource import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "containerregistry",
  "mod": "index/resource",
  "fqn": "pulumi_containerregistry",
  "classes": {
   "containerregistry:index/resource:Resource": "Resource"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "containerregistry",
  "token": "pulumi:providers:containerregistry",
  "fqn": "pulumi_containerregistry",
  "class": "Provider"
 }
]
"""
)
