// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Containerregistry
{
    [ContainerregistryResourceType("containerregistry:index/resource:Resource")]
    public partial class Resource : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Image tarball thing.
        /// </summary>
        [Output("image")]
        public Output<AssetOrArchive> Image { get; private set; } = null!;

        /// <summary>
        /// Hash of the image tarball.
        /// </summary>
        [Output("imageTarballHash")]
        public Output<string?> ImageTarballHash { get; private set; } = null!;

        /// <summary>
        /// The tag to save the image to.
        /// </summary>
        [Output("remoteTag")]
        public Output<string> RemoteTag { get; private set; } = null!;


        /// <summary>
        /// Create a Resource resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Resource(string name, ResourceArgs args, CustomResourceOptions? options = null)
            : base("containerregistry:index/resource:Resource", name, args ?? new ResourceArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Resource(string name, Input<string> id, ResourceState? state = null, CustomResourceOptions? options = null)
            : base("containerregistry:index/resource:Resource", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/rhysmdnz/pulumi-containerregistry",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Resource resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Resource Get(string name, Input<string> id, ResourceState? state = null, CustomResourceOptions? options = null)
        {
            return new Resource(name, id, state, options);
        }
    }

    public sealed class ResourceArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Image tarball thing.
        /// </summary>
        [Input("image", required: true)]
        public Input<AssetOrArchive> Image { get; set; } = null!;

        /// <summary>
        /// Hash of the image tarball.
        /// </summary>
        [Input("imageTarballHash")]
        public Input<string>? ImageTarballHash { get; set; }

        /// <summary>
        /// The tag to save the image to.
        /// </summary>
        [Input("remoteTag", required: true)]
        public Input<string> RemoteTag { get; set; } = null!;

        public ResourceArgs()
        {
        }
        public static new ResourceArgs Empty => new ResourceArgs();
    }

    public sealed class ResourceState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Image tarball thing.
        /// </summary>
        [Input("image")]
        public Input<AssetOrArchive>? Image { get; set; }

        /// <summary>
        /// Hash of the image tarball.
        /// </summary>
        [Input("imageTarballHash")]
        public Input<string>? ImageTarballHash { get; set; }

        /// <summary>
        /// The tag to save the image to.
        /// </summary>
        [Input("remoteTag")]
        public Input<string>? RemoteTag { get; set; }

        public ResourceState()
        {
        }
        public static new ResourceState Empty => new ResourceState();
    }
}
