name: Upgrade provider
on:
  workflow_dispatch:
  issues:
    types:
    - opened
  schedule:
    - cron: '0 5 * * *'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version-file: "provider/go.mod"
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@main
